# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hamilton_starlet_pb2 as hamilton__starlet__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hamilton_starlet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HamiltonMicrolabSTARletStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFeatureInfo = channel.unary_unary(
                '/sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet/GetFeatureInfo',
                request_serializer=hamilton__starlet__pb2.GetFeatureInfoRequest.SerializeToString,
                response_deserializer=hamilton__starlet__pb2.GetFeatureInfoResponse.FromString,
                _registered_method=True)
        self.GetParameters = channel.unary_unary(
                '/sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet/GetParameters',
                request_serializer=hamilton__starlet__pb2.GetParametersRequest.SerializeToString,
                response_deserializer=hamilton__starlet__pb2.GetParametersResponse.FromString,
                _registered_method=True)
        self.SetParameters = channel.unary_unary(
                '/sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet/SetParameters',
                request_serializer=hamilton__starlet__pb2.SetParametersRequest.SerializeToString,
                response_deserializer=hamilton__starlet__pb2.SetParametersResponse.FromString,
                _registered_method=True)
        self.ExecuteMethod = channel.unary_unary(
                '/sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet/ExecuteMethod',
                request_serializer=hamilton__starlet__pb2.ExecuteMethodRequest.SerializeToString,
                response_deserializer=hamilton__starlet__pb2.ExecuteMethodResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet/GetStatus',
                request_serializer=hamilton__starlet__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=hamilton__starlet__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.GetAuditTrail = channel.unary_stream(
                '/sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet/GetAuditTrail',
                request_serializer=hamilton__starlet__pb2.GetAuditTrailRequest.SerializeToString,
                response_deserializer=hamilton__starlet__pb2.AuditTrailEntry.FromString,
                _registered_method=True)


class HamiltonMicrolabSTARletServicer:
    """Missing associated documentation comment in .proto file."""

    def GetFeatureInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditTrail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HamiltonMicrolabSTARletServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFeatureInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatureInfo,
                    request_deserializer=hamilton__starlet__pb2.GetFeatureInfoRequest.FromString,
                    response_serializer=hamilton__starlet__pb2.GetFeatureInfoResponse.SerializeToString,
            ),
            'GetParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameters,
                    request_deserializer=hamilton__starlet__pb2.GetParametersRequest.FromString,
                    response_serializer=hamilton__starlet__pb2.GetParametersResponse.SerializeToString,
            ),
            'SetParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.SetParameters,
                    request_deserializer=hamilton__starlet__pb2.SetParametersRequest.FromString,
                    response_serializer=hamilton__starlet__pb2.SetParametersResponse.SerializeToString,
            ),
            'ExecuteMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteMethod,
                    request_deserializer=hamilton__starlet__pb2.ExecuteMethodRequest.FromString,
                    response_serializer=hamilton__starlet__pb2.ExecuteMethodResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=hamilton__starlet__pb2.GetStatusRequest.FromString,
                    response_serializer=hamilton__starlet__pb2.GetStatusResponse.SerializeToString,
            ),
            'GetAuditTrail': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAuditTrail,
                    request_deserializer=hamilton__starlet__pb2.GetAuditTrailRequest.FromString,
                    response_serializer=hamilton__starlet__pb2.AuditTrailEntry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HamiltonMicrolabSTARlet:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFeatureInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet/GetFeatureInfo',
            hamilton__starlet__pb2.GetFeatureInfoRequest.SerializeToString,
            hamilton__starlet__pb2.GetFeatureInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet/GetParameters',
            hamilton__starlet__pb2.GetParametersRequest.SerializeToString,
            hamilton__starlet__pb2.GetParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet/SetParameters',
            hamilton__starlet__pb2.SetParametersRequest.SerializeToString,
            hamilton__starlet__pb2.SetParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet/ExecuteMethod',
            hamilton__starlet__pb2.ExecuteMethodRequest.SerializeToString,
            hamilton__starlet__pb2.ExecuteMethodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet/GetStatus',
            hamilton__starlet__pb2.GetStatusRequest.SerializeToString,
            hamilton__starlet__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditTrail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sila2_bridge.hamilton_starlet.HamiltonMicrolabSTARlet/GetAuditTrail',
            hamilton__starlet__pb2.GetAuditTrailRequest.SerializeToString,
            hamilton__starlet__pb2.AuditTrailEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
